### ISSUE TITLE
Explain sentence in readme

### ISSUE THREAD

**Issue by rauschma** [malyw/es-modules-utils#1]
I don’t understand what this means (possibly also mention why it is useful):

> `add-global-class`: the binary attribute, if present makes the script to add the 'esmodules'/'no-esmodules' HTML classes to `<html>` element depending on the ES modules support in the browser

**Comment by shospodarets** [comment]
I rewrote the README with:

> add-global-class: the binary attribute, which enables adding the <html class="esmodules"> if ES modules are supported, <html class="no-esmodules"> otherwise (can be used e.g. to show some animation till the ES module is loaded)

Also, the new options were added:

> add-global-variable: the binary attribute, which enables adding the global Boolean variable window.esmodules=true/false (can be used e.g. to decide which method to use to include new scripts)

Let me know if it's easier to read and more straightforward.
