### ISSUE TITLE
Firefox Nightly triggers both scripts

### ISSUE THREAD

**Issue by brownieboy** [malyw/es-modules-utils#2]
I'm using Firefox Nightly 55.0a1 with the dom.moduleScripts.enabled flag set to true to give ES6 module loader support.

Opening your https://blog.hospodarets.com/es-modules-utils/demo/ test page, both the "supported" and the "unsupported" alert boxes are triggered.

**Comment by shospodarets** [comment]
Hi @brownieboy . Thanks for checking that.
This will be fixed as only the Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=1330900 is resolved.
The plan is that none browsers ship ECMAScript modules to the stable version till nomodule attribute support is added.
